[[target]]
    name = "tictactoe_playdate" # hyphens will not work. See https://github.com/pd-rs/crankstart/issues/89
    assets = [
        "assets/_background.png",
        "assets/_cross.png",
        "assets/_game_over.png",
        "assets/_game_tied.png",
        "assets/_hand.png",
        "assets/_level_1.png",
        "assets/_level_2.png",
        "assets/_level_3.png",
        "assets/_level_4.png",
        "assets/_level_5.png",
        "assets/_level_6.png",
        "assets/_level_7.png",
        "assets/_nought.png",
        "assets/_player_loses.png",
        "assets/_player_wins.png",
        "assets/card.png",
        "assets/launchImage.png",
    ]
    [target.metadata]
    name = "TicTacToe"
    version = "0.1.0"
    author = "missfunmi"
    bundle_id = "com.missfunmi.tictactoe"
    description = "😈TicTacToe: A classic game with increasingly chaotic levels"
